Repository toufikforyou/banglalikhi.com, pull requests merged in 2025-01, with the labels that each got.

#1 Bengali alphabet and voyel files
  src/ts/bengali-alphabet-compositions.ts
  src/ts/bengali-vowel-compositions.ts
  wrangler.toml
Labels: enhancement

#11 Feature/publisher Update name, add description, license, keyword pkj.json
  package.json
  src/functions/index.ts
  tsconfig.json
Labels: documentation

#12 Update package.json to change name, add description, license, keyword
  package.json
  src/functions/index.ts
  tsconfig.json
Labels: good first issue

#13 Feat: Action for npm package
  .github/workflows/release.yml
  .gitignore
  .npmignore
  package.json
  release.config.cjs
  src/bijoy2unicode/index.ts
  src/converter/index.ts
  src/converters/bijoy-converter.ts
  src/converters/unicode-converter.ts
  src/functions/index.ts
  src/unicode2bijoy/index.ts
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#14 Feat: Development Action for npm package
  .github/workflows/release.yml
  .gitignore
  .npmignore
  package.json
  release.config.cjs
  src/bijoy2unicode/index.ts
  src/converter/index.ts
  src/converters/bijoy-converter.ts
  src/converters/unicode-converter.ts
  src/functions/index.ts
  src/unicode2bijoy/index.ts
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#15 Add step to install dependencies in GitHub Actions workflow
  .github/workflows/release.yml
Labels: bug

#16 Feat: Action for npm package Development to main
  .github/workflows/release.yml
Labels: enhancement

#17 feat: Add development branch to GitHub Actions release workflow
  .github/workflows/release.yml
Labels: enhancement

#18 feat: Add GITHUB_TOKEN to release workflow for semantic-release
  .github/workflows/release.yml
Labels: enhancement

#19 feat: Refactor: index.ts and update tsconfig
  .github/workflows/release.yml
  index.ts
  tsconfig.build.json
Labels: good first issue

#20 feat: update build output directory and package metadata
  .npmignore
  LICENSE
  package.json
  release.config.cjs
  tsconfig.build.json
Labels: good first issue

#21 feat: include 'lib' directory in package files
  package.json
Labels: good first issue

#23 refactor: remove unused files and update package metadata
  .github/workflows/release.yml
  .gitignore
  .npmignore
  index.ts
  package.json
  release.config.cjs
  tsconfig.build.json
Labels: enhancement

#24 refactor: remove unused files and update package metadata
  .github/workflows/release.yml
  .gitignore
  .npmignore
  index.ts
  package.json
  release.config.cjs
  tsconfig.build.json
Labels: enhancement

#25 chore: update project name in wrangler configuration
  wrangler.toml
Labels: enhancement
